version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: rehbar_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rehbar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  nextjs:
    build:
      context: ./rehbar
      dockerfile: Dockerfile.dev
    container_name: rehbar_next_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/rehbar_db?schema=public"
      NODE_ENV: development
      WATCHPACK_POLLING: true
    volumes:
      # Mount the entire project directory to enable live reloading
      - ./rehbar:/app
      # Use named volumes for better cross-platform compatibility
      - node_modules:/app/node_modules
      - next_cache:/app/.next
      - yarn_cache:/app/.yarn
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  node_modules:
  next_cache:
  yarn_cache: